definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: -44
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
  user__page:
    weight: -50
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
  user__logout:
    weight: -49
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
langcode: fr
