display_configuration:
  link_text: 'Media selecteren'
widgets:
  6586703a-6976-4124-8a49-cbb07ceaa3b1:
    settings:
      submit_text: 'Media selecteren'
  ecb3940b-e53b-4bc5-acb5-930d8780ea2f:
    label: 'Nieuwe afbeelding uploaden'
